version: '3.3'
services:

  # Infrastructure
  # ============================================================================
  # Config server
  config-server:
    image: sashimi/spring-petclinic-config-server
    container_name: sashimi-config-server
    entrypoint: ["sh", "-c","
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8888:8888

  # Discovery service
  discovery-server:
    image: sashimi/spring-petclinic-discovery-server
    container_name: sashimi-discovery-server
    depends_on:
      - config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8761:8761

  # Services
  # ============================================================================
  # Customers service
  customers-service:
    image: sashimi/spring-petclinic-customers-service
    container_name: sashimi-customers-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8081:8081

  # Visits service
  visits-service:
    image: sashimi/spring-petclinic-visits-service
    container_name: sashimi-visits-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8082:8082

  #Vets service
  vets-service:
    image: sashimi/spring-petclinic-vets-service
    container_name: sashimi-vets-service
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8083:8083

  # API gateway
  api-gateway:
    image: sashimi/spring-petclinic-api-gateway
    container_name: sashimi-api-gateway
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
      - 8080:8080

  # Admin Server
  # ============================================================================
  admin-server:
    image: sashimi/spring-petclinic-admin-server
    container_name: sashimi-admin-server
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
     - 9090:9090

  # Circuit breaker
  # ============================================================================
  hystrix-dashboard:
    image: sashimi/spring-petclinic-hystrix-dashboard
    container_name: sashimi-hystrix-dashboard
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
      -jar /app.jar"]
    ports:
     - 7979:7979

  # Load
  # ============================================================================
  # Load server
  load-server:
    build: ./docker/load-server
    image: sashimi/load-server
    container_name: sashimi-load-server
    depends_on:
      - api-gateway
      - customers-service
      - visits-service
      - vets-service
