version: '3.3'
services:

  # Infrastructure
  # ============================================================================
  # Config server
  config-server:
    image: sashimi-benchmark/spring-petclinic-config-server
    container_name: sashimi-benchmark-config-server
    volumes:
      - /home/adrian/.m2:/root/.m2
    entrypoint: ["sh", "-c","
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false 
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8888:8888

  # Discovery service
  discovery-server:
    image: sashimi-benchmark/spring-petclinic-discovery-server
    container_name: sashimi-benchmark-discovery-server
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
      - config-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8761:8761

  # Services
  # ============================================================================
  # Customers service
  customers-service:
    image: sashimi-benchmark/spring-petclinic-customers-service
    container_name: sashimi-benchmark-customers-service
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8081:8081

  # Visits service
  visits-service:
    image: sashimi-benchmark/spring-petclinic-visits-service
    container_name: sashimi-benchmark-visits-service
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8082:8082

  #Vets service
  vets-service:
    image: sashimi-benchmark/spring-petclinic-vets-service
    container_name: sashimi-benchmark-vets-service
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8083:8083

  # API gateway
  api-gateway:
    image: sashimi-benchmark/spring-petclinic-api-gateway
    container_name: sashimi-benchmark-api-gateway
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://discovery-server:8761 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
      - 8080:8080

  # Admin Server
  # ============================================================================
  admin-server:
    image: sashimi-benchmark/spring-petclinic-admin-server
    container_name: sashimi-benchmark-admin-server
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
     - 9090:9090

  # Circuit breaker
  # ============================================================================
  hystrix-dashboard:
    image: sashimi-benchmark/spring-petclinic-hystrix-dashboard
    container_name: sashimi-benchmark-hystrix-dashboard
    volumes:
      - /home/adrian/.m2:/root/.m2
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["sh", "-c","
      ./dockerize -wait=tcp://config-server:8888 -timeout=300s -- &&
      java -jar /app.jar --thin.dryrun --thin.root=. &&
      java -noverify 
      -XX:+UnlockExperimentalVMOptions 
      -XX:+UseCGroupMemoryLimitForHeap 
      -XX:TieredStopAtLevel=1 
      -Dspring.jmx.enabled=false
      -Djava.security.egd=file:/dev/./urandom 
      -jar /app.jar 
      --thin.root=. 
      --thin.dryrun=false"]
    ports:
     - 7979:7979

  # Load
  # ============================================================================
  # Load server
  load-server:
    build: ./docker/load-server
    image: sashimi-benchmark/load-server
    container_name: sashimi-benchmark-load-server
    depends_on:
      - api-gateway
      - customers-service
      - visits-service
      - vets-service
